apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: sample-app
      ports:
        - port: 443
        - port: 80  
  policyTypes:
  - Ingress
